# These are supported funding model platforms

patreon: ScriptKKiddie
open_collective: shobhit-sharma
custom: ['https://buymeacoffee.com/shobhitsharma','https://www.getrevue.co/profile/scriptkkiddie/members']
