# These are supported funding model platforms

patreon: ScriptKKiddie
open_collective: scriptkkiddie
custom: ['https://www.buymeacoffee.com/ScriptKKiddie','https://www.getrevue.co/profile/scriptkkiddie/members']
